on:
  push

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java
        with:
          java-version: 1.11
      - name: Test clean build
        run: ./gradlew clean build